export const MK_F_DISPLAY_FEE_DEFINITION_FORM = "MK_F_DISPLAY_FEE_DEFINITION_FORM";
export const MK_F_HIDE_FEE_DEFINITON_FORM = "MK_F_HIDE_FEE_DEFINITON_FORM";

export const MK_F_SET_VALUE = "MK_F_SET_VALUE";
export const MK_F_SET_NAME = "MK_F_SET_NAME";
export const MK_F_SET_DESCRIPTION = "MK_F_SET_DESCRIPTION";

export const MK_F_DISPLAY_FEE_MARKETS_FORM = "MK_F_DISPLAY_FEE_MARKETS_FORM";
export const MK_F_HIDE_FEE_MARKETS_FORM = "MK_F_HIDE_FEE_MARKETS_FORM";

export const MK_F_SET_MARKET_FEE_MODE = "MK_F_SET_MARKET_FEE_MODE";
